{{ if .Values.cronjobs.transferCreation.enabled }}
{{ range $index, $schedule := .Values.cronjobs.transferCreation.schedules }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%d" "transfer-creation" $index }}
  labels:
    application: stairling
    component: transfer-creation
    {{ include "backend.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- if $.Values.vault.enabled }}
            vault.security.banzaicloud.io/vault-addr: {{ $.Values.vault.url | quote }}
            vault.security.banzaicloud.io/vault-role: {{ $.Values.vault.role | quote }}
            vault.security.banzaicloud.io/vault-skip-verify: {{ $.Values.vault.skipVerify | quote }}
            {{- if and $.Values.vault.envFrom.enabled $.Values.vault.envFrom.path }}
            vault.security.banzaicloud.io/vault-env-from-path: {{ $.Values.vault.envFrom.path }}
            {{- end }}
            {{- end }}
        spec:
          containers:
            - image: {{ include "backend.image.transferCreation" $ }}
              imagePullPolicy: IfNotPresent
              name: transfer-creation
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccountName: {{ (include "backend.serviceAccountName" $) | lower }}
          terminationGracePeriodSeconds: 30
  schedule: {{ $schedule | quote }}
  successfulJobsHistoryLimit: 3
  suspend: false
{{ end }}
{{ end }}