apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  | default "stairling" }}
  labels:
    control-plane: kafka-controller
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    application: stairling
    component: backend
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port:  443
      protocol: TCP
      targetPort: api
