apiVersion: v1
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc }}
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
type: Opaque