apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{ include "postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    application: postgresql
    {{ include "postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port:  5432
      protocol: TCP
      targetPort: postgres
