apiVersion: v1
kind: ServiceAccount
  {{- if .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.image.pullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "outbox.serviceAccountName" . }}
  labels:
  {{- include "outbox.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
