apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  | default "webhook-gateway" }}
  labels:
    control-plane: kafka-controller
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    application: stairling
    component: backend
    {{- include "webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port:  8080
      protocol: TCP
      targetPort: http
