# charts/stairling-backend/Chart.yaml
apiVersion: v2
appVersion: 1.4.0
description: Chart Created by David ALEXANDRE <david.alexandre@w6d.io>
home: https://stairling.com
sources:
  - https://charts.stairling.bluelabs.fr
keywords:
- backend
- stairling
maintainers:
- email: david@stairling.com
  name: david972
name: stairling-backend
version: 1.0.33
